Repository ACM-Research/online-portfolio-selection, pull requests merged in 2021-04, with the labels that each got.

#24 Kernel-Based Log-Optimal Strategy
  olps/datasources/kernel_based_datasource.py
  olps/strategies/kernel_based_log_optimal_strategy.py
  olps/strategies/kernel_based_semi_log_optimal_strategy.py
  tests/test_kernel_based_datasource.py
  tests/test_kernel_based_log_optimal_strategy.py
  tests/test_kernel_based_semi_log_strategy.py
Labels: enhancement

#23 Anti-Correlation Strategy & Tests
  olps/datasources/ac_datasource.py
  olps/strategies/ac_strategy.py
  requirements.txt
  tests/test_ac_strategy.py
Labels: enhancement

#26 hotfix: Remove hardcoded references, make it possible to run multiday merge tasks
  olps/data_preprocessor/__main__.py
Labels: bug

#29 Fully tested CORN Implementation
  olps/datasources/correlation_driven_datasource.py
  olps/strategies/correlation_driven_log_optimal_strategy.py
  tests/test_correlation_driven_datasource.py
  tests/test_correlation_driven_log_optimal_strategy.py
Labels: enhancement

#31 Feature: Make Visualizer abstract and move Cumulative Return Graph to separate file
  olps/visualization/crg_visualizer.py
  olps/visualization/visualizer.py
Labels: enhancement

#32 OLMAR Implementation
  olps/datasources/olmar_datasource.py
  olps/strategies/olmar_strategy.py
  tests/test_OLMAR_datasource.py
  tests/test_olmar_strategy.py
Labels: enhancement, strategy-implementation

#34 Improved CRG Visualization labels
  olps/visualization/crg_visualizer.py
Labels: enhancement

#36 Bar Graph Feature + CORN fixes/ test + Simple Backtest
  backtests/mar29toapril1test_bar.py
  olps/datasources/correlation_driven_datasource.py
  olps/strategies/correlation_driven_log_optimal_strategy.py
  olps/visualization/brg_visualizer.py
  results/mar29toapril1_BAH_BST/mar29toapril1-wealth-BAHStrategy.txt
  results/mar29toapril1_BAH_BST/mar29toapril1-wealth-BestStockStrategy.txt
  results/mar29toapril1_BAH_BST/out.png
  tests/test_correlation_driven_datasource.py
  tests/test_correlation_driven_log_optimal_strategy.py
Labels: backtest, enhancement, strategy-implementation

#38 Feature: Visualization - Animated CRG
  backtests/mar29toapril1test_animated.py
  olps/visualization/animated_crg_visualizer.py
Labels: enhancement

#39 hotfix: Handle overlapping ticks
  olps/market/mdp.py
  olps/market/tm.py
Labels: bug
