Repository ACM-Research/online-portfolio-selection, pull requests merged in 2021-03, with the labels that each got.

#1 feature: Initial strategy boilerplate
  README.md
  olps/datasources/datasource.py
  olps/strategies/strategy.py
  requirements.txt
  setup.py
  tests/test_datasource.py
  tests/test_strategy.py
Labels: enhancement

#10 Strategy wealth fix
  olps/strategies/strategy.py
  tests/test_strategy.py
Labels: bug

#11 feature: BAH Strategy tests
  olps/strategies/bah_strategy.py
  tests/test_bah_strategy.py
Labels: enhancement, strategy-implementation
